from django.urls import path
from .views import (
    AssignTechnicianView,
    AuthLoginView,
    AuthLogoutView,
    AuthSessionView,
    PasswordSetupView,
    UserProfileView,
    DashboardSummaryView,
    MemorialListView,
    MemorialManageListCreateView,
    CustomerListView,
    CemeteryListView,
    CemeteryManageListCreateView,
    TechnicianListView,
    SchedulingServiceListView,
    SchedulingServiceCreateView,
    CompleteServiceView,
    PhotoArchiveListView,
    ServiceOptionListCreateView,
    ServiceOptionDetailView,
    ServicePhotoUploadView,
    SendCustomerEmailView,
    CustomerManageListCreateView,
    CustomerManageDetailView,
    EmployeeRoleListView,
    EmployeeRoleDetailView,
    EmployeeInviteResendView,
    EmployeeCreateView,
    CustomerInvoiceListView,
    AdminInvoiceListView,
    AdminInvoiceSendView,
    CreateCheckoutSessionView,
    VerifyCheckoutSessionView,
    ServiceSurveyDetailView,
    PublicSurveyDetailView,
)

urlpatterns = [
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/logout/", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/session/", AuthSessionView.as_view(), name="auth-session"),
    path("auth/password-setup/", PasswordSetupView.as_view(), name="auth-password-setup"),
    path("auth/profile/", UserProfileView.as_view(), name="auth-profile"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("memorials/", MemorialListView.as_view(), name="memorial-list"),
    path("manage/memorials/", MemorialManageListCreateView.as_view(), name="manage-memorials"),
    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("cemeteries/", CemeteryListView.as_view(), name="cemetery-list"),
    path("manage/cemeteries/", CemeteryManageListCreateView.as_view(), name="manage-cemeteries"),
    path("technicians/", TechnicianListView.as_view(), name="technician-list"),
    path("scheduling/services/", SchedulingServiceListView.as_view(), name="scheduling-service-list"),
    path("scheduling/services/create/", SchedulingServiceCreateView.as_view(), name="scheduling-service-create"),
    path("photos/", PhotoArchiveListView.as_view(), name="photo-archive-list"),
    path("manager/services/<int:service_id>/complete/", CompleteServiceView.as_view(), name="service-complete"),
    path("manager/services/<int:service_id>/photos/", ServicePhotoUploadView.as_view(), name="service-photo-upload"),
    path("service-options/", ServiceOptionListCreateView.as_view(), name="service-option-list"),
    path("emails/send/", SendCustomerEmailView.as_view(), name="emails-send"),
    path("manage/customers/", CustomerManageListCreateView.as_view(), name="manage-customers"),
    path("manage/customers/<int:customer_id>/", CustomerManageDetailView.as_view(), name="manage-customer-detail"),
    path("manage/service-options/", ServiceOptionListCreateView.as_view(), name="manage-service-options"),
    path("manage/service-options/<int:service_option_id>/", ServiceOptionDetailView.as_view(), name="manage-service-option-detail"),
    path("manage/employees/", EmployeeRoleListView.as_view(), name="manage-employees"),
    path("manage/employees/create/", EmployeeCreateView.as_view(), name="manage-employees-create"),
    path("manage/employees/<int:employee_id>/invite/resend/", EmployeeInviteResendView.as_view(), name="manage-employee-invite-resend"),
    path("manage/employees/<int:employee_id>/", EmployeeRoleDetailView.as_view(), name="manage-employee-detail"),
    path("manage/invoices/", AdminInvoiceListView.as_view(), name="manage-invoices"),
    path("manage/invoices/<int:invoice_id>/send/", AdminInvoiceSendView.as_view(), name="manage-invoice-send"),
    path("manage/services/<int:service_id>/survey/", ServiceSurveyDetailView.as_view(), name="manage-service-survey"),
    path("customer/invoices/", CustomerInvoiceListView.as_view(), name="customer-invoices"),
    path("public/surveys/<str:token>/", PublicSurveyDetailView.as_view(), name="public-survey-detail"),
    path("payments/checkout-session/", CreateCheckoutSessionView.as_view(), name="payments-checkout-session"),
    path("payments/checkout-session/verify/", VerifyCheckoutSessionView.as_view(), name="payments-checkout-session-verify"),
    path("manager/services/<int:service_id>/assign/", AssignTechnicianView.as_view()),
]
