# Generated by Django 5.2.6 on 2026-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
