# Generated by Django 6.0.1 on 2026-03-25 02:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_service_options(apps, schema_editor):
    ServiceOption = apps.get_model('core', 'ServiceOption')
    Service = apps.get_model('core', 'Service')
    defaults = [
        ('Cleaning', 'cleaning', 10),
        ('Reset', 'reset', 20),
        ('Leveling', 'leveling', 30),
        ('Repair', 'repair', 40),
        ('Engraving', 'engraving', 50),
        ('Other', 'other', 60),
    ]
    for name, legacy_key, sort_order in defaults:
        option, _ = ServiceOption.objects.update_or_create(
            legacy_key=legacy_key,
            defaults={'name': name, 'sort_order': sort_order, 'is_active': True},
        )
        Service.objects.filter(service_type=legacy_key, service_option__isnull=True).update(service_option=option)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('legacy_key', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='plot',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='plot',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='service_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.serviceoption'),
        ),
        migrations.RunPython(seed_service_options, migrations.RunPython.noop),
    ]
