# Generated by Django 6.0.1 on 2026-04-01 21:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_photo_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSurveyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_request', to='core.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cemetery_name', models.CharField(blank=True, max_length=255)),
                ('cemetery_address', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('row', models.CharField(blank=True, max_length=50)),
                ('plot_number', models.CharField(blank=True, max_length=50)),
                ('grave_number', models.CharField(blank=True, max_length=50)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('locating_notes', models.TextField(blank=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='survey_photos/')),
                ('survey_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.customersurveyrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
