# Generated by Django 6.0.1 on 2026-04-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customersurveyrequest_customersurveysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
